spring:
  datasource:
    url: jdbc:mysql://139.224.3.128:3306/lk_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: zhangyan
    password: Zy1256=

platform:
  zhongtai:
    baseUrl: https://tgwb.95538.cn
    appId: d46c7c8104bc498f9e71bb8e9038ec5e
    appKey: 1c91721427b34407994c84e2a1e51be9
    secretKey: b99b45d5c9ac18780542640019364b5929bc144ffe8e070426b3172ff742188f

  guoxin:
    baseUrl: https://zctg.guosen.com.cn/xxl
    manager_id: 5764
    app_id: lktz
    sec_key: LKTZGLBJYXGS202204191703sc

  guotai:
    BaseUrl: https://pb.gtja.com/pbapi/api


  zhaoshang:
    BserUrl: http://210.21.237.135:27011/v1/request
    companyId: 6576f2d94b3f4b76bca7863739438392
    uap_server_type: 668
    uap_user_no: client_LiangKeTouZi_BeiJing
    uap_licence_key: 2286bc68-2547-4a59-8178-e03049f85c69
    pfxFilePath: E:/lk_project_dev/lk_product_management/conf/zs.pfx
    pfxFilePwd: lktz123