spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankbalance?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: rootroot

