spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankbalance?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: abc

platform:
  zhongtai:
    baseUrl: https://tgwb.95538.cn
    appId: d46c7c8104bc498f9e71bb8e9038ec5e
    appKey: 1c91721427b34407994c84e2a1e51be9
    secretKey: b99b45d5c9ac18780542640019364b5929bc144ffe8e070426b3172ff742188f